name: Python to EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Wähle deine Python-Version

    - name: Install PyInstaller and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller tkinter-tooltip # Füge hier alle benötigten Bibliotheken hinzu

    - name: Build the EXE
      run: pyinstaller --noconsole mypingyv5

    - name: Upload the EXE
      uses: actions/upload-artifact@v4
      with:
        name: mypingyv5-exe
        path: dist/mypingyv5.exe
